databases:
  - name: legoapp-db
    plan: free
    databaseName: legoapp
    user: legoapp

services:
  - type: web
    name: legoapp-web
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: legoapp-db
          property: connectionString

      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DJANGO_DEBUG
        value: "0"

      - key: DJANGO_ALLOWED_HOSTS
        value: "legoapp-web.onrender.com"
